select * FROM all_objects  ao 
where ao.OBJECT_TYPE = 'PACKAGE'  and owner not in ('APEX_030200', 'SYSMAN', 
'EXFSYS', 'AUDSYS','SYS','SYSBACKUP','SYSDG','SYSKM','SYSTEM','OUTLN','GSMADMIN_INTERNAL','GSMUSER',
'DIP','XS$NULL','ORACLE_OCM','DBSNMP','APPQOSSYS','ANONYMOUS','XDB','GMCATUSER','WMSYS','OJVMSYS','CTXSYS',
'MDSYS','ORDDATA','ORDPLUGINS','ORDSYS','SI_INFORMTN_SCHEMA','OLAPSYS','MDDATA','SPATIAL_WFS_ADMIN_USR','SPATIAL_CSW_ADMIN_UR',
'LBACSYS','APEX_040200','APEX_PUBLIC_USER','FLOWS_FILES','DVF','DVSYS', 'SDE', 'SPOT')