
-- buscar o nome
select * from siuca.usuario su 
left join  siuca.usuario_base_dados_geoc ug on su.id_usuario = ug.id_usuario
where UPPER(su.nome_usuario) like 'ALIN%';

-- 
select  rowid, s.* FROM siuca.setor_orgao s;

insert into siuca.setor_orgao (id_setor_orgao, desc_setor, sigla_setor, nome_unid_organizacional, sigla_unid_organizacional) values 
(57, 'Gerência de Licenciamento Urbanístico', 'GELU', 'EMPRESA DE TRANSPORTE E TRANSITO DE BH',  'BHTRANS');

commit;  --57



-- inserir os dados na tabela de usuario
insert into SIUCA.USUARIO SU (DATA_CADASTRO_USUARIO , MATRICULA_USUARIO, NOME_USUARIO, DESC_CARGO  
, TEL_USUARIO, EMAIL_USUARIO,SITUACAO_USUARIO, ID_SETOR_ORGAO) values(
sysdate,
'bt0013681',
upper('Pedro Henrique de Oliveira Santos'),
'Funcionario',
'3279 7972',
'pedrongint@gmail.com',
'ATIVO',
57
);

commit;


-- tabela de usuarios do oracle
-- verificar se o usuario existe

select * FROM all_users au where au.username like 'SIBELLE'


-- inserir os dados na tabela do siuca
select * from siuca.usuario_base_dados_geoc;


declare
   result_s smallint;
begin
  -- Call the function
  result_s := siuca.fu_cria_usuario_bdgc(941,'sena@pbh.gov.br', 1574338);
end;

--

-- atribuiir as roles
SELECT * FROM DBA_ROLES  dr where  dr.ROLE like '%SELECT_MUB_V2%';

select * FROM dba_role_privs  rp where rp.GRANTED_ROLE = 'UPDATE_LANC_PRELIMINAR'
 
-- privs de uma role
SELECT * FROM dba_tab_privs d  where d.grantee =UPPER('SELECT_MUB_V2');


grant SELECT_MUB_V2 to ANETE_ALVAREZ; 
grant SELECT_MUB_V2 to SENA; 
grant SELECT_MUB_V2 to PEDRONGINT; 

create role  UPDATE_TRANSITO;


grant UPDATE_TRANSITO to ANETE_ALVAREZ; 
grant UPDATE_TRANSITO to SENA; 
grant UPDATE_TRANSITO to PEDRONGINT; 
grant UPDATE_TRANSITO to SIBELLE; 

select  'GRANT DELETE, INSERT, UPDATE ON '||owner||'.'||table_name||' TO UPDATE_TRANSITO; ' 
  from all_tables where owner = 'TRANSITO'
  and table_name not like 'MDRT%' and table_name not like 'MDXT%'  --CROQUI_TRIBUTARIO_V
  

SE mdsys.sdo_geom_metadata_table m


-- SELECT  



GRANT SELECT, DELETE, INSERT, UPDATE ON TRANSITO.HIST_DISTRIBUIDOR TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.DISTRIBUIDOR TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.HIST_TIPO_DESTINACAO TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.HIST_TEMPO_PERMANENCIA TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.HIST_REGULAMENTACAO_FX TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.HIST_REGRA_OPERACAO_FX TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.HIST_REGRA_OPERACAO TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.HIST_PROJETO_OPERACIONAL TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.HIST_POSTO_VENDA_ROTATIVO TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.HIST_PERDO_REGRA_OPERACAO TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.HIST_FX_PARADA_ESTACION TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.HIST_AREA_PROJ_OPRACIONAL TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.HIST_ALINHAMENTO_ESTACION TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.TIPO_DESTINACAO TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.TEMPO_PERMANENCIA TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.REGULAMENTACAO_FX TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.REGRA_OPERACAO_FX TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.REGRA_OPERACAO TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.PROJETO_OPERACIONAL TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.POSTO_VENDA_ROTATIVO TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.PERIODO_REGRA_OPERACAO TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.FX_PARADA_ESTACION TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.AREA_PROJ_OPERACIONAL TO UPDATE_TRANSITO; 
GRANT DELETE, INSERT, UPDATE ON TRANSITO.ALINHAMENTO_ESTACION TO UPDATE_TRANSITO;


GRANT update (GEOMETRIA) ON TRANSITO.POSTO_VENDA_ROTATIVO to ANETE_ALVAREZ;
GRANT update (GEOMETRIA) ON TRANSITO.POSTO_VENDA_ROTATIVO to SENA;
GRANT update (GEOMETRIA) ON TRANSITO.POSTO_VENDA_ROTATIVO to PEDRONGINT;
GRANT update (GEOMETRIA) ON TRANSITO.POSTO_VENDA_ROTATIVO to SIBELLE;



select * FROM  mdsys.sdo_geom_metadata_table m
where M.SDO_OWNER = 'TRANSITO'
 


create role SELECT_LANC_PRELIM_SEM_IPTU;

GRANT select ON LANCAMENTO_PRELIMINAR.LP_CTM_SEM_IPTU_COM_CP TO SELECT_LANC_PRELIM_SEM_IPTU;


grant SELECT_LANC_PRELIM_SEM_IPTU to GEIDER;
grant SELECT_LANC_PRELIM_SEM_IPTU to IZABELA_JARDIM;
grant SELECT_LANC_PRELIM_SEM_IPTU to ALINECAMPOSSILVA;
grant SELECT_LANC_PRELIM_SEM_IPTU to ANGELO;


