select * from dba_tab_columns 
where DATA_TYPE NOT IN ('NUMBER', 'VARCHAR2')
and OWNER NOT IN ('SYS', 'SYSTEM', 'WMSYS', 'DBSNMP', 'APPQOSSYS', 'XDB', 'MAPINFO', 'ORDSYS', 'CTXSYS', 'OUTLN', 'OLAPSYS', 'ORDDATA', 'EXFSYS', 'MDSYS', 'SYSMAN', 'APEX_030200'
, 'FLOWS_FILES', 'GDOSYS', 'TSMSYS' )


SELECT  OWNER 
from dba_tab_columns  
GROUP BY OWNER;

SELECT  OWNER 
from dba_tab_columns  
GROUP BY OWNER;


select DATA_TYPE from dba_tab_columns 
where DATA_TYPE NOT IN ('NUMBER', 'VARCHAR2')
and OWNER NOT IN ('SYS', 'SYSTEM', 'WMSYS', 'DBSNMP', 'APPQOSSYS', 'XDB', 'MAPINFO', 'ORDSYS', 'CTXSYS', 'OUTLN', 'OLAPSYS', 'ORDDATA', 'EXFSYS', 'MDSYS', 'SYSMAN', 'APEX_030200'
, 'FLOWS_FILES', 'GDOSYS', 'TSMSYS' )
group by DATA_TYPE


SELECT * FROM GERMEM.HIST_CABO;
